# Generated by Django 5.0.6 on 2024-06-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_section'),
        ('school', '0004_alter_registration_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section_teacher',
            unique_together={('course', 'semester', 'teacher', 'section')},
        ),
    ]
