# Generated by Django 5.0.6 on 2024-06-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_coursegrades_class_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrades',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='school.registration'),
        ),
    ]
